CREATE TABLE `actions` (
  `id` integer not null primary key autoincrement,
  `hand_id` integer not null,
  `player_id` integer not null,
  `action_type` text check (`action_type` in ('fold',
  'check',
  'call',
  'bet',
  'raise',
  'all_in',
  'small_blind',
  'big_blind')) not null,
  `amount` integer not null default '0',
  `round` text check (`round` in ('preflop',
  'flop',
  'turn',
  'river')) not null,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime not null default CURRENT_TIMESTAMP,
  `sequence_number` integer not null default '0',
  foreign key(`hand_id`) references `hands`(`id`) on delete CASCADE,
  foreign key(`player_id`) references `players`(`id`) on delete CASCADE
)