CREATE TABLE "games" (
  `id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
  `room_code` varchar(6) NOT NULL,
  `status` text NOT NULL CHECK (`status` in('waiting',
  'active',
  'completed')) DEFAULT 'waiting',
  `small_blind` integer NOT NULL DEFAULT '5',
  `big_blind` integer NOT NULL DEFAULT '10',
  `starting_chips` integer NOT NULL DEFAULT '1000',
  `dealer_position` integer NOT NULL DEFAULT '0',
  `current_round` text NULL CHECK (`current_round` in('preflop',
  'flop',
  'turn',
  'river',
  'showdown')),
  `pot` integer NOT NULL DEFAULT '0',
  `community_cards` json NULL,
  `current_bet` integer NOT NULL DEFAULT '0',
  `current_player_position` integer NULL,
  `hand_number` integer NOT NULL DEFAULT '0',
  `last_raise` integer NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `deck` text NULL,
  `winners` text NULL,
  `showdown_processed` boolean NOT NULL DEFAULT '0',
  `action_finished` boolean NOT NULL DEFAULT '0',
  `seed` text NULL,
  `room_id` integer NOT NULL,
  `game_number` integer NOT NULL DEFAULT '1',
  FOREIGN KEY (`room_id`) REFERENCES `rooms` (`id`) ON DELETE CASCADE
)