CREATE TABLE `game_players` (
  `id` integer not null primary key autoincrement,
  `game_id` integer not null,
  `room_player_id` integer not null,
  `position` integer not null,
  `chips` integer not null default '1000',
  `current_bet` integer not null default '0',
  `total_bet` integer not null default '0',
  `hole_cards` json null,
  `status` text check (`status` in ('active',
  'folded',
  'all_in',
  'out')) not null default 'active',
  `is_dealer` boolean not null default '0',
  `is_small_blind` boolean not null default '0',
  `is_big_blind` boolean not null default '0',
  `show_cards` boolean not null default '0',
  `last_action` text check (`last_action` in ('fold',
  'check',
  'call',
  'bet',
  'raise',
  'all_in')) null,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime not null default CURRENT_TIMESTAMP,
  foreign key(`game_id`) references `games`(`id`) on delete CASCADE,
  foreign key(`room_player_id`) references `room_players`(`id`) on delete CASCADE
)