CREATE TABLE "game_players" (
  `room_player_id` integer not null,
  `game_id` integer not null,
  `position` integer not null,
  `chips` integer not null default '0',
  `current_bet` integer not null default '0',
  `total_bet` integer not null default '0',
  `hole_cards` json null,
  `status` varchar(255) not null default 'active' check (`status` in ('active',
  'folded',
  'all_in',
  'out',
  'sitting_out')),
  `is_dealer` boolean not null default '0',
  `is_small_blind` boolean not null default '0',
  `is_big_blind` boolean not null default '0',
  `show_cards` boolean not null default '0',
  `last_action` varchar(255) null,
  `created_at` datetime not null default CURRENT_TIMESTAMP,
  `updated_at` datetime not null default CURRENT_TIMESTAMP,
  foreign key(`room_player_id`) references `room_players`(`id`) on delete CASCADE,
  foreign key(`game_id`) references `games`(`id`) on delete CASCADE,
  primary key (`room_player_id`,
  `game_id`)
)